name: Reciever of the release

on:
  repository_dispatch:
    types: [hlae_update_again]

jobs:
  transport:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # 获取原仓库的版本
    - name: Get Latest HLAE Tag
      uses: actions-hub/watch-tag@master
      with:
         provider: github
         repository: advancedfx/advancedfx
         env_name: LATEST_HLAE_TAG

    # 下载API文件
    - name: Download File To Workspace
      uses: carlosperate/download-file-action@v1.0.3
      with:
        # URL of the file to download
        file-url: https://api.github.com/repos/advancedfx/advancedfx/releases/latest
        # New filename to rename the downloaded file
        file-name: release.json
        #location: # optional, default is .

    # 运行工具
    - name: Run Repo-Tranporter
      run: |
        ls -al
        chmod 777 repo-transporter
        ./repo-transporter
        ls -al
    
    - name: push
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: master
        commit-message: 'Automatically pushed by GitHub Actions'
        rebase: 'true' # pull abd rebase before commit
        force-add: 'true'
        name: Purple-CSGO
        email: 438518244@qq.com
    
    - name: dir
      run: |
        ls -al
        
    # 等待15s 以防先发布再push
    - name: Sleep for 15 seconds
      uses: jakejarvis/wait-action@master
      with:
        time: '15s'
    
    # 运行工具
    - name: Github Release create, update, and upload assets
      uses: meeDamian/github-release@v2.0.3
      env:
        TAG: 'v${{ env.LATEST_HLAE_TAG }}'
      with:
        token:  ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.TAG }}
        name: ${{ env.TAG }}
        body: This release is automatically made by GitHub Actions


